
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { TravelPlanData } from "@/types/travel";
import { MapPin, Calendar, Users, Ticket, DollarSign } from "lucide-react";

interface TravelPlanProps {
  plan: TravelPlanData;
}

const TravelPlan = ({ plan }: TravelPlanProps) => {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card className="bg-sky-50 border-sky-200">
          <CardContent className="pt-6">
            <div className="flex items-center gap-2 mb-2">
              <MapPin className="h-5 w-5 text-sky-700" />
              <h3 className="font-medium text-sky-900">Trip Summary</h3>
            </div>
            <div className="space-y-2 text-sky-800">
              <p><span className="font-medium">From:</span> {plan.summary.source}</p>
              <p><span className="font-medium">To:</span> {plan.summary.destination}</p>
              <p><span className="font-medium">Duration:</span> {plan.summary.duration}</p>
              <p><span className="font-medium">Best time to visit:</span> {plan.summary.bestTimeToVisit}</p>
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-sky-50 border-sky-200">
          <CardContent className="pt-6">
            <div className="flex items-center gap-2 mb-2">
              <DollarSign className="h-5 w-5 text-sky-700" />
              <h3 className="font-medium text-sky-900">Budget</h3>
            </div>
            <div className="space-y-2 text-sky-800">
              <p><span className="font-medium">Total Budget:</span> {plan.budget.total}</p>
              <p><span className="font-medium">Accommodations:</span> {plan.budget.accommodation}</p>
              <p><span className="font-medium">Transportation:</span> {plan.budget.transportation}</p>
              <p><span className="font-medium">Food & Activities:</span> {plan.budget.foodAndActivities}</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Separator className="bg-sky-200" />
      
      <div className="space-y-6">
        <div className="flex items-center gap-2">
          <Calendar className="h-5 w-5 text-sky-700" />
          <h3 className="text-lg font-semibold text-sky-900">Itinerary</h3>
        </div>
        
        {plan.itinerary.map((day, index) => (
          <Card key={index} className="bg-white border-sky-100">
            <CardContent className="pt-6">
              <h4 className="font-semibold text-sky-800 mb-3">Day {day.day}: {day.title}</h4>
              <div className="space-y-4">
                {day.activities.map((activity, actIndex) => (
                  <div key={actIndex} className="border-l-2 border-sky-300 pl-4 py-1">
                    <h5 className="font-medium text-sky-700">{activity.time} - {activity.title}</h5>
                    <p className="text-gray-600 text-sm mt-1">{activity.description}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Separator className="bg-sky-200" />
      
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <Ticket className="h-5 w-5 text-sky-700" />
          <h3 className="text-lg font-semibold text-sky-900">Recommendations</h3>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {plan.recommendations.map((rec, index) => (
            <Card key={index} className="bg-white border-sky-100">
              <CardContent className="pt-6">
                <h4 className="font-semibold text-sky-800">{rec.category}</h4>
                <ul className="list-disc list-inside mt-2 space-y-1 text-gray-600">
                  {rec.items.map((item, itemIndex) => (
                    <li key={itemIndex}>{item}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      <div className="mt-6 bg-blue-50 border border-blue-200 rounded-md p-4 text-blue-800 text-sm">
        <p className="italic">This travel plan was generated by AI based on your preferences. 
        You may want to verify details like prices, opening hours, and availability before finalizing your trip.</p>
      </div>
    </div>
  );
};

export default TravelPlan;
